CREATE DATABASE ST_LOGIN;

CREATE  TABLE ST_LOGIN1
(

USERNAME  VARCHAR(50) PRIMARY KEY NOT NULL,
PASSWORD    NVARCHAR(50) NOT NULL
);

SELECT * FROM ST_LOGIN1;
 INSERT INTO ST_LOGIN1 VALUES ( 'STUDENT', 'AIUB2021');

DELETE FROM ST_LOGIN1 WHERE USERNAME = '  ';
