CREATE DATABASE ST_LOGIN;

CREATE  TABLE TR_INFORMATION
(
TeacherId INT PRIMARY KEY,
TeacherName VARCHAR(50) ,
Age int,
Department VARCHAR(50),
Religion NVARCHAR(50),
PresentAddress NVARCHAR(50),
PhoneNumber NVARCHAR(50),
BloodGroup NVARCHAR(50),
Picture  IMAGE

);

SELECT * FROM TR_INFORMATION;

DELETE FROM TR_INFORMATION WHERE  TEACHERID  = ' 121 ';