CREATE DATABASE ST_LOGIN;

CREATE  TABLE TR_LOGIN
(

USERNAME  VARCHAR(50) PRIMARY KEY NOT NULL,
PASSWORD    NVARCHAR(50) NOT NULL
);

SELECT * FROM TR_LOGIN;
 INSERT INTO TR_LOGIN VALUES ( 'TEACHER', 'AIUB2021');


